version: "3"

services:
  a-backend-service:
    image: brreg/template-image-name:latest
    depends_on:
      - mongodb
    restart: always
    environment:
      - TEMPLATE_MONGO_USERNAME=admin
      - TEMPLATE_MONGO_PASSWORD=admin
      - TEMPLATE_MONGO_HOST=mongodb:27017
    ports:
      - 8138:8080
