openapi: 3.0.2
info:
  title: A backend service API
  description: A generic example of an API
  version: '1.0'
  termsOfService: 'https://fellesdatakatalog.brreg.no/about'
  contact:
    name: Brønnøysundregistrene
    url: 'https://fellesdatakatalog.brreg.no'
    email: fellesdatakatalog@brreg.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
externalDocs:
  description: Documentation
  url: https://informasjonsforvaltning.github.io/
tags:
  - name: version
    description: Gives information on commits, branches etc for this service.
  - name: serviceEndpoints
    description: Store and gives a list of service endpoints it has verion information on
servers:
  - url: 'https://fellesdatakatalog.brreg.no'
paths:
  /version:
    get:
      tags:
        - version
      summary: Get version information about this service.
      description: Returns a version object with SHA, branch name and build date.
      operationId: getVersion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
  /serviceendpoints:
    get:
      tags:
        - serviceEndpoints
      summary: Get a list of service endpoints that this service monitors.
      description: Returns a list of endpoints (server urls)
      operationId: getServiceEndpoints
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceEndpointCollection'
components:
  schemas:
    Version:
      type: object
      description: A version object
      properties:
        repositoryName:
          type: string
          description: The name of the remote repository
        branchName:
          type: string
          description: The name of the branch the service was built from
        buildTime:
          type: string
          description: The timestamp the build was created
        sha:
          type: string
          description: The commit the service was built from
        versionId:
          type: string
          description: The POM version the service was built from
    ServiceEndpointCollection:
      type: object
      description: A list of service endpoints
      properties:
        total:
          type: integer
          description: the number of elements in the collection
        serviceEndpoints:
          type: array
          items:
            $ref: '#/components/schemas/ServiceEndpoint'
    ServiceEndpoint:
      type: object
      properties:
        name:
          type: string
          description: the name of the service (repository name)
        url:
          type: string
          format: uri
          description: the url to a service endpoint that is monitored
