openapi: 3.0.2
info:
  title: National Data Directory Template API
  description: A generic example of an API
  version: '1.0'
  termsOfService: 'https://fellesdatakatalog.brreg.no/about'
  contact:
    name: Brønnøysundregistrene
    url: 'https://fellesdatakatalog.brreg.no'
    email: fellesdatakatalog@brreg.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
externalDocs:
  description: Dokumentasjon på Informasjonsforvaltning GitHub
  url: https://informasjonsforvaltning.github.io/felles-datakatalog/datasett-katalog/api/
tags:
  - name: version
    description: Version service
servers:
  - url: 'https://fellesdatakatalog.brreg.no'
paths:
  /version:
    get:
      tags:
        - version
      summary: Get version information about this service.
      description: Returns a version object with SHA, branch name and date
      operationId: getVersion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
components:
  schemas:
    Version:
      type: object
      description: A version object
      properties:
        repositoryName:
          type: string
          description: The name of the remote repository
        branchName:
          type: string
          description: The name of the branch the service was built from
        buildTime:
          type: string
          description: The timestamp the build was created
        sha:
          type: string
          description: The commit the service was built from
        versionId:
          type: string
          description: The POM version the service was built from
