apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: a-back-end-service
  name: a-back-end-service
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: a-back-end-service
status:
  loadBalancer: {}
