name: Deploy to staging when pull request is created

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn clean install -B -T 2C
      - name: Tag Docker image
        run: |
        docker tag brreg/a-backend-service:latest eu.gcr.io/fdk-infra/brreg/a-backend-service:latest
        docker tag brreg/a-backend-service:latest eu.gcr.io/fdk-infra/brreg/a-backend-service:staging_latest
        docker tag brreg/a-backend-service:latest eu.gcr.io/fdk-infra/brreg/a-backend-service:$GITHUB_SHA
      - name: Push docker image to Google Cloud
        uses: actions/gcloud/cli@master
        env:
          PROJECT_ID: fdk-infra
          APPLICATION_NAME: myproject
        with:
          runs: "sh -c"
          args: "docker -- push eu.gcr.io/fdk-infra/a-backend-service:$GITHUB_SHA"
      - name: Apply Helm template
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.14.3
          command: |
            helm init --client-only
            helm repo add fdk https://informasjonsforvaltning.github.io/helm-chart/
            helm fetch --untar --untardir ./helm fdk/a-backend-service
            helm template --set DOCKER_IMAGE_NAME="eu.gcr.io/fdk-infra/a-backend-service:$GITHUB_SHA" -f ./helm/a-backend-service/values/staging.yaml ./helm/a-backend-service/ > ./kubectlapply.yaml
            cat ./kubectlapply.yaml
            chmod o+w ./kubectlapply.yaml
            cat kubectlapply.yaml
      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.FDK_DEV_AUTODEPLOY }}
          project_id: fdk-dev
          location_zone: europe-north1-a
          cluster_name: fdk-dev
      - name: Deploy to staging
        uses: docker://bitnami/kubectl:latest
        env:
          KUBECONFIG: '/github/workspace/.kube/config'
        with:
          args: "apply -f ./kubectlapply.yaml --force"
      - name: Notify slack of deploy
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
          args: '{\"channel\":\"C7NTH118T\",\"text\":\"Application: a-backend-service deployed to staging\"}'