name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Package with maven
        run: mvn clean package --no-transfer-progress

      - name: Build Docker image
        run: docker build -f Dockerfile.prod . -t eu.gcr.io/fdk-infra/a-backend-service:latest

      - name: Run tests
        run: mvn verify --no-transfer-progress